/**
 * DashboardPageElement.ts — pages/client/dashboard/
 *
 * Full spec implementation (replaces Part 4's proof-of-concept).
 *
 * Composes:
 *   - PeriodSelectorElement (period filter)
 *   - KpiMetricPickerElement (metric selection with period-over-period deltas)
 *   - ChartWidgetElement (bar/line/area toggle + skeleton loading)
 *   - 5 ReportShortcutTiles (accordion: only one expanded at a time)
 *   - Contextual insight line (auto-generated by DashboardService)
 *
 * Data source: DashboardService (interface-injected, backed by real or mock
 * DashboardRepository depending on VITE_USE_MOCK_DATA).
 *
 * Accordion behavior:
 *   Only one report tile's breakdown is open at a time. This is coordinated
 *   HERE, not in the tile component — a tile doesn't know about its siblings.
 *
 * Period-over-period deltas:
 *   Next to each selected KPI chip, an ↑/↓ arrow + percentage is rendered.
 *   This uses the same comparison data as the insight line — computed once
 *   by DashboardService, not recomputed separately.
 */
import { BaseComponent } from '../../../platform/component/BaseComponent';
import { ComponentRegistry } from '../../../platform/component/ComponentRegistry';
import { injectStyles, injectGlobalTokens } from '../../../platform/component/ShadowRenderMixin';
import { html, SafeHtmlString } from '../../../platform/rendering/SafeHtml';
import { dashboardService, suggestionService } from '../../../services';
import type { DashboardSummary } from '../../../services/DashboardService';
import { DateRange } from '../../../core/value-objects/DateRange';
import type { ReportTileData } from '../../../components/report-shortcut-tile/ReportShortcutTileElement';

interface ChartWidgetHost extends HTMLElement {
  data: { label: string; value: number }[];
  chartType: 'bar' | 'line' | 'area';
  isLoading: boolean;
}

interface KpiMetricPickerHost extends HTMLElement {
  selectedMetrics: string[];
}

interface LoadingStateHost extends HTMLElement {
  variant: 'spinner' | 'skeleton';
  shape: 'table-rows' | 'chart' | 'card';
}

interface PeriodSelectorHost extends HTMLElement {
  selectedPeriod: string;
}

interface ReportTileHost extends HTMLElement {
  tileData: ReportTileData;
  expanded: boolean;
}

const STYLES = `
  :host { display: block; font-family: var(--font-body); }
  .dashboard-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: var(--space-6);
  }
  .dashboard-title {
    font-size: var(--font-size-2xl);
    font-weight: var(--font-weight-bold);
    color: var(--color-text-primary);
    margin: 0;
  }
  .dashboard-controls {
    display: flex;
    align-items: center;
    gap: var(--space-3);
  }
  .chart-type-toggle {
    display: flex;
    gap: var(--space-1);
  }
  .chart-type-btn {
    padding: var(--space-1) var(--space-3);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    background: var(--color-bg);
    cursor: pointer;
    font-size: var(--font-size-xs);
    font-family: var(--font-body);
  }
  .chart-type-btn.active {
    background: var(--color-primary);
    color: var(--color-primary-foreground);
    border-color: var(--color-primary);
  }
  .insight-line {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-left: 3px solid var(--color-primary);
    border-radius: var(--radius-md);
    padding: var(--space-3) var(--space-4);
    margin-bottom: var(--space-4);
    font-size: var(--font-size-sm);
    color: var(--color-text-primary);
  }
  .kpi-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
    gap: var(--space-3);
    margin-bottom: var(--space-6);
  }
  .kpi-card {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    padding: var(--space-4);
  }
  .kpi-label {
    font-size: var(--font-size-xs);
    color: var(--color-text-muted);
    text-transform: uppercase;
    letter-spacing: 0.03em;
    margin: 0 0 var(--space-1);
  }
  .kpi-value {
    font-size: var(--font-size-xl);
    font-weight: var(--font-weight-bold);
    color: var(--color-text-primary);
    margin: 0;
  }
  .kpi-delta {
    font-size: var(--font-size-xs);
    font-weight: var(--font-weight-semibold);
    margin-top: var(--space-1);
  }
  .kpi-delta.up { color: var(--color-success); }
  .kpi-delta.down { color: var(--color-danger); }
  .kpi-delta.flat { color: var(--color-text-muted); }
  .chart-section {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    padding: var(--space-4);
    margin-bottom: var(--space-6);
  }
  .chart-title {
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-semibold);
    color: var(--color-text-primary);
    margin: 0 0 var(--space-3);
  }
  .report-tiles {
    display: flex;
    flex-direction: column;
    gap: var(--space-3);
  }
  .low-network-notice {
    background: var(--color-warning-bg, #fef3c7);
    border: 1px solid var(--color-warning-border, #f59e0b);
    border-radius: var(--radius-md);
    padding: var(--space-3);
    font-size: var(--font-size-sm);
    color: var(--color-warning-text, #92400e);
    margin-bottom: var(--space-4);
  }
`;

const REPORT_TILES: { key: string; label: string }[] = [
  { key: 'day', label: 'By Day' },
  { key: 'exchange', label: 'By Exchange' },
  { key: 'os', label: 'By OS' },
  { key: 'campaign', label: 'By Campaign' },
  { key: 'creative', label: 'By Creative' },
];

class DashboardPageElement extends BaseComponent {
  private isLoading = true;
  private summary: DashboardSummary | null = null;
  private selectedMetrics = ['Impressions', 'Clicks', 'Spend', 'Revenue'];
  private chartType: 'bar' | 'line' | 'area' = 'bar';
  private currentPeriod: DateRange = DateRange.fromPeriodOption('7d');
  private expandedTileKey: string | null = null;

  constructor() {
    super();
    injectGlobalTokens(this.shadow);
    injectStyles(this.shadow, STYLES);
  }

  protected onMount(): void {
    this.shadow.addEventListener('period-changed', this.handlePeriodChanged);
    this.shadow.addEventListener('metrics-changed', this.handleMetricsChanged);
    this.shadow.addEventListener('tile-clicked', this.handleTileClicked);
    this.shadow.addEventListener('click', this.handleClick);
    this.addEventListener('suggestion-accepted', this.handleSuggestionAccepted);
    void this.loadSummary();
  }

  protected onUnmount(): void {
    this.shadow.removeEventListener('period-changed', this.handlePeriodChanged);
    this.shadow.removeEventListener('metrics-changed', this.handleMetricsChanged);
    this.shadow.removeEventListener('tile-clicked', this.handleTileClicked);
    this.shadow.removeEventListener('click', this.handleClick);
    this.removeEventListener('suggestion-accepted', this.handleSuggestionAccepted);
  }

  private async loadSummary(): Promise<void> {
    this.isLoading = true;
    this.rerender();
    this.syncLoadingState();
    try {
      this.summary = await dashboardService.getDashboardSummary(this.currentPeriod);
    } catch {
      this.summary = null;
    }
    this.isLoading = false;
    this.rerender();
    this.syncChildComponents();
    // Trigger AI suggestion checkpoint — page load with existing data
    this.dispatchSuggestionCheckpoint();
  }

  private handleSuggestionAccepted = async (event: Event): Promise<void> => {
    const ce = event as CustomEvent<{ suggestionId: string }>;
    if (!ce.detail) return;
    try {
      await suggestionService.acceptSuggestion(ce.detail.suggestionId);
      void this.loadSummary();
    } catch {
      // Suggestion acceptance is non-critical — silently fail
    }
  };

  private dispatchSuggestionCheckpoint(): void {
    document.dispatchEvent(
      new CustomEvent('suggestion-checkpoint', {
        detail: { source: 'dashboard', entityType: 'campaign', clientId: 'client-1' },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private syncLoadingState(): void {
    const loading = this.shadow.querySelector<LoadingStateHost>('loading-state');
    if (loading) {
      loading.variant = 'skeleton';
      loading.shape = 'chart';
    }
  }

  private syncChildComponents(): void {
    if (this.isLoading || !this.summary) return;
    const chart = this.shadow.querySelector<ChartWidgetHost>('chart-widget');
    if (chart) {
      chart.data = this.summary.chartData;
      chart.chartType = this.chartType;
      chart.isLoading = false;
    }
    const picker = this.shadow.querySelector<KpiMetricPickerHost>('kpi-metric-picker');
    if (picker) {
      picker.selectedMetrics = this.selectedMetrics;
    }
    const period = this.shadow.querySelector<PeriodSelectorHost>('period-selector');
    if (period) {
      period.selectedPeriod = '7d';
    }
    this.syncExpandedTile();
  }

  private syncExpandedTile(): void {
    if (!this.expandedTileKey || !this.summary) return;
    const tile = this.shadow.querySelector<ReportTileHost>(`[data-tile-key="${this.expandedTileKey}"]`);
    if (tile) {
      tile.tileData = this.buildTileData(this.expandedTileKey);
      tile.expanded = true;
    }
  }

  private buildTileData(tileKey: string): ReportTileData {
    const chartData = this.summary?.chartData ?? [];
    return {
      label: REPORT_TILES.find((t) => t.key === tileKey)?.label ?? tileKey,
      chartData,
      tableRows: chartData.map((d, i) => ({ label: d.label, value: d.value, index: i + 1 })),
      tableColumns: [
        { key: 'label', label: 'Label' },
        { key: 'value', label: 'Value' },
        { key: 'index', label: '#' },
      ],
    };
  }

  private handlePeriodChanged = (event: Event): void => {
    const detail = (event as CustomEvent<DateRange>).detail;
    if (detail) {
      this.currentPeriod = detail;
      void this.loadSummary();
    }
  };

  private handleMetricsChanged = (event: Event): void => {
    const detail = (event as CustomEvent<string[]>).detail;
    this.selectedMetrics = detail;
    this.rerender();
    this.syncChildComponents();
  };

  private handleTileClicked = (event: Event): void => {
    const detail = (event as CustomEvent<{ label: string; expanded: boolean }>).detail;
    if (detail.expanded) {
      this.expandedTileKey = REPORT_TILES.find((t) => t.label === detail.label)?.key ?? null;
    } else {
      this.expandedTileKey = null;
    }
    this.rerender();
    this.syncAllTiles();
  };

  private handleClick = (event: Event): void => {
    const target = event.target as HTMLElement;
    const chartTypeBtn = target.closest('[data-chart-type]');
    if (chartTypeBtn) {
      const type = chartTypeBtn.getAttribute('data-chart-type') as 'bar' | 'line' | 'area';
      if (type) {
        this.chartType = type;
        const chart = this.shadow.querySelector<ChartWidgetHost>('chart-widget');
        if (chart) chart.chartType = type;
        this.rerender();
      }
    }
  };

  private syncAllTiles(): void {
    for (const tile of REPORT_TILES) {
      const el = this.shadow.querySelector<ReportTileHost>(`[data-tile-key="${tile.key}"]`);
      if (el) {
        el.expanded = tile.key === this.expandedTileKey;
        if (el.expanded) {
          el.tileData = this.buildTileData(tile.key);
        }
      }
    }
  }

  private renderKpiCards(): string {
    if (!this.summary) return '';
    return this.selectedMetrics
      .filter((m) => m in this.summary!.kpiValues)
      .map((m) => {
        const value = this.summary!.kpiValues[m]!;
        const delta = this.summary!.deltas[m];
        let deltaHtml = '';
        if (delta) {
          const arrow = delta.direction === 'up' ? '↑' : delta.direction === 'down' ? '↓' : '–';
          deltaHtml = `<p class="kpi-delta ${delta.direction}">${arrow} ${Math.abs(delta.value)}%</p>`;
        }
        return `<div class="kpi-card"><p class="kpi-label">${m}</p><p class="kpi-value">${value.toLocaleString()}</p>${deltaHtml}</div>`;
      })
      .join('');
  }

  private renderReportTiles(): string {
    return REPORT_TILES.map((tile) => {
      const expanded = tile.key === this.expandedTileKey;
      return `<report-shortcut-tile data-tile-key="${tile.key}" ${expanded ? 'data-expanded' : ''}></report-shortcut-tile>`;
    }).join('');
  }

  protected renderTemplate(): string {
    if (this.isLoading) {
      return html`
        <div class="dashboard-header">
          <h1 class="dashboard-title">Dashboard</h1>
        </div>
        <loading-state variant="skeleton" shape="chart"></loading-state>
      `;
    }

    if (!this.summary) {
      return html`
        <div class="dashboard-header">
          <h1 class="dashboard-title">Dashboard</h1>
        </div>
        <empty-state message="No dashboard data available"></empty-state>
      `;
    }

    return html`
      <div class="dashboard-header">
        <h1 class="dashboard-title">Dashboard</h1>
        <div class="dashboard-controls">
          <period-selector></period-selector>
        </div>
      </div>
      <div class="insight-line">${this.summary.insight}</div>
      <kpi-metric-picker></kpi-metric-picker>
      <div class="kpi-grid">${SafeHtmlString.trusted(this.renderKpiCards())}</div>
      <div class="chart-section">
        <p class="chart-title">Performance Overview</p>
        <div class="chart-type-toggle">
          <button class="chart-type-btn ${this.chartType === 'bar' ? 'active' : ''}" data-chart-type="bar" type="button">Bar</button>
          <button class="chart-type-btn ${this.chartType === 'line' ? 'active' : ''}" data-chart-type="line" type="button">Line</button>
          <button class="chart-type-btn ${this.chartType === 'area' ? 'active' : ''}" data-chart-type="area" type="button">Area</button>
        </div>
        <chart-widget></chart-widget>
      </div>
      <div class="report-tiles">${SafeHtmlString.trusted(this.renderReportTiles())}</div>
      <ai-suggestion-popup></ai-suggestion-popup>
    `;
  }
}

ComponentRegistry.register('client-dashboard', DashboardPageElement);
export { DashboardPageElement };